public class Manager extends Employee{
    public static void handleTeam(){
        
    }
    public static void ensureDeliverability(){
        
    }
    public static void handleEscalations(){
        
    }
    Public static void handleAppraisals(){
        
    }
    public override void markAttendance(){
        System.debug('Marked present for Manager who is also an employee');
    }
    

}